name: CI

# Controls when the action will run.
# For GITHUB_TOKEN and PAT, the permissions are granted based on the role of the token.
# For example, a job that needs to push to the repository will require the "contents: write" permission.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # Job ID, determines the workflow run's status.
  build-and-test:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    # Steps can be executed directly or through use of "actions" that are reusable, open-source versions of a Git.
    # Or, in this case, a reusable version of an action that someone else wrote:
    # https://github.com/actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'uv'

      - name: Install dependencies with uv
        run: |
          python -m uv --no-cachear 
          python -m uv pip install -r requirements.txt

      - name: Lint with Ruff
        run:
          python -m uv pip install ruff
          ruff check .

      - name: Run tests with Pytest
        run:
          python -m uv pip install pytest
          pytest


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
